### ISSUE TITLE
Cannot find module '@author.io/args'

### ISSUE THREAD

**Issue by endm** [coreybutler/node-windows#308]
Hi, I could install my service, but I can´t start it

This is my error detail.

Error: Cannot find module '@author.io/args'
Require stack:
- C:\Program Files\nodejs\node_modules\node-windows\lib\wrapper.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\node-windows\lib\wrapper.js:3:12)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Program Files\\nodejs\\node_modules\\node-windows\\lib\\wrapper.js'
  ]
}

**Comment by coreybutler** [comment]
Are you importing node-windows directly, i.e. `require('node-windows')`? The issue you're experiencing is one I came across in development, but only when using local references (i.e. `require('../')`).

**Comment by endm** [comment]
This is my install.js. It's the same as example.

```
var Service = require('node-windows').Service;
var dir = require('path').join(process.cwd(), 'app.js')

var svc = new Service({
  name:'SielconBDCasino',
  description: 'Sielcon BD Casino (MQTT Broker)',
  script: dir,
  env:{
    name: "NODE_ENV",
    value: "production"
  }
});

// Listen for the "install" event, which indicates the
// process is available as a service.
svc.on('install',function(){
  svc.start();
});

// Just in case this file is run twice.
svc.on('alreadyinstalled',function(){
  console.log('This service is already installed.');
});

// Listen for the "start" event and let us know when the
// process has actually started working.
svc.on('start',function(){
  console.log(svc.name+' started!');
});

// Install the script as a service.
console.log("Installing to", dir)
svc.install();
```

**Comment by alexmarginet** [comment]
I am experiencing the same issue. I could not make it work with version `1.0.0-beta.7`, instead I had to force version `1.0.0-beta,6`.
I am not sure about this but it seems that `lib/wrapper.js` contains a typo when importing the `Args = require('@author.io/args')` .
Unless I am missing something, that line should reference `@author.io/arg` instead

**Comment by fengssy** [comment]
> I am experiencing the same issue. I could not make it work with version 1.0.0-beta.7, instead I had to force version 1.0.0-beta,6.

me too

**Comment by bidule21** [comment]
> I am experiencing the same issue. I could not make it work with version `1.0.0-beta.7`, instead I had to force version `1.0.0-beta,6`.

Same here

**Comment by amralaa-MSFT** [comment]
> @author.io/arg

Same

**Comment by coreybutler** [comment]
There is a typo in the wrapper file causing this problem... but there is also a conflict. The arg lib uses ESM-only, while this module still supports CommonJS.

I will create a CJS version of the arg lib to resolve this problem for now, but it will take me a day or two. In the meantime, I recommend using 1.0.0-beta.6 until that is complete.

I've also started a discussion to capture community feedback regarding the direction of this project. Please comment at https://github.com/coreybutler/node-windows/discussions/309#discussion-3955262.

**Comment by esbenvb** [comment]
Downgrading to **1.0.0-beta.6** solved it for me

**Comment by lingyuj** [comment]
same here

**Comment by gngo2018** [comment]
Is there any update on this one lately?

**Comment by coreybutler** [comment]
I've been backed up with client projects. I've done part of the arg lib conversion, but am not finished yet.

**Comment by ctaylor28** [comment]
> Hi I read that on April 6th the 1.0.0.beta.7 version should have been fixed. But I have just installed the package on a fresh VM and I still see the error 1067 issue when starting the service.
> 
> file *.err.log shows "Error: Cannot find module '@author.io/args'"
> 
> Am I missing anything?
> 
> Thanks a lot for your valuable work

I still see the issue too

**Comment by gngo2018** [comment]
Reverting to beta 6 does work, however, shows vulnerability errors due to the optimist package. Does anyone know of a workaround for the vulnerability?

**Comment by declan-wade** [comment]
> I am experiencing the same issue. I could not make it work with version 1.0.0-beta.7, instead I had to force version 1.0.0-beta,6.

Exact same

**Comment by baconbrad** [comment]
@coreybutler Would [Yargs](http://yargs.js.org/) be a suitable replacement? The license is compatible.

**Comment by coreybutler** [comment]
@baconbrad I'm sure yargs might work, but I wrote the author/arg lib. If another security vulnerability comes up, I can address it (unlike other libraries).

I know folks want this fixed. I want to fix it, but I have pressing client work taking precedence at the moment.

**Comment by baconbrad** [comment]
@coreybutler Understandable I didn't initially realize the aim was for a dependency free parser and thought it was just to ditch a known vulnerable one.

**Comment by scdba** [comment]
@coreybutler - this is a fantastic project !

Just managed to get 1.0.0-beta.6 working
1.0.0-beta.7 has the Cannot find module '@author.io/args' issue

> I know folks want this fixed. I want to fix it... but client work is taking precedence at the moment.

tell me about it ;)

I will wait patiently for 1.0.0-beta.8

**Comment by Vimlesh22** [comment]
I am experiencing the same issue. I could not make it work with version 1.0.0-beta.7 or 1.0.0-beta.6 either.

**Comment by amoscatelli** [comment]
Also, I noticed that '@author.io/args' version 1.3.22, the one used in node-windows package.json, is actually in empty folder when you install it with npm.

In other words it's missing index.js.

If you upgrade to 1.3.23 index.js can be found.

Rollbacking to beta 6 for now.

**Comment by RichardD2** [comment]
Beta 6 no longer works for me.

I have two Windows Server 2019 servers, with Node 16.15, npm 8.8.0, and node-windows 1.0.0-beta.6. One one computer, the `npm link node-windows` command works. On the other it fails.

> npm WARN ERESOLVE overriding peer dependency
> npm WARN While resolving: @apollo/client@3.6.1
> npm WARN Found: graphql-ws@4.9.0
> npm WARN node_modules/graphql-ws
> npm WARN   graphql-ws@"^4.4.1" from @graphql-tools/url-loader@6.10.1
> npm WARN   node_modules/@graphql-tools/url-loader
> npm WARN     @graphql-tools/url-loader@"^6.3.1" from graphql-tools@7.0.0
> npm WARN     node_modules/graphql-tools
> npm WARN
> npm WARN Could not resolve dependency:
> npm WARN peerOptional graphql-ws@"^5.5.5" from @apollo/client@3.6.1
> npm WARN node_modules/@apollo/client
> npm WARN   @apollo/client@"^3.1.5" from apollo-upload-client@14.1.2
> npm WARN   node_modules/apollo-upload-client
> npm WARN
> npm WARN Conflicting peer dependency: graphql-ws@5.9.0
> npm WARN node_modules/graphql-ws
> npm WARN   peerOptional graphql-ws@"^5.5.5" from @apollo/client@3.6.1
> npm WARN   node_modules/@apollo/client
> npm WARN     @apollo/client@"^3.1.5" from apollo-upload-client@14.1.2
> npm WARN     node_modules/apollo-upload-client
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR!
> npm ERR! While resolving: apollo-link-persisted-queries@0.2.2
> npm ERR! Found: graphql@15.3.0
> npm ERR! node_modules/graphql
> npm ERR!   peer graphql@"^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0" from apollo-cache-control@0.14.0
> npm ERR!   node_modules/apollo-cache-control
> npm ERR!     apollo-cache-control@"^0.14.0" from apollo-server-core@2.25.3
> npm ERR!     node_modules/apollo-server-core
> npm ERR!       apollo-server-core@"^2.25.2" from apollo-server@2.25.2
> npm ERR!       node_modules/apollo-server
> npm ERR!         apollo-server@"2.25.2" from the root project
> npm ERR!       2 more (apollo-server-express, apollo-server-express)
> npm ERR!   peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0" from apollo-client@2.6.10
> npm ERR!   node_modules/apollo-client
> npm ERR!     peer apollo-client@"^2.0.0" from vue-apollo@3.0.5
> npm ERR!     node_modules/vue-apollo
> npm ERR!       dev vue-apollo@"3.0.5" from the root project
> npm ERR!     dev apollo-client@"2.6.10" from the root project
> npm ERR!   70 more (apollo-cache, apollo-cache-inmemory, apollo-link, ...)
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from apollo-link-persisted-queries@0.2.2
> npm ERR! node_modules/apollo-link-persisted-queries
> npm ERR!   dev apollo-link-persisted-queries@"0.2.2" from the root project
> npm ERR!
> npm ERR! Conflicting peer dependency: graphql@14.7.0
> npm ERR! node_modules/graphql
> npm ERR!   peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from apollo-link-persisted-queries@0.2.2
> npm ERR!   node_modules/apollo-link-persisted-queries
> npm ERR!     dev apollo-link-persisted-queries@"0.2.2" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

I don't want to learn the intricacies of Node to try to debug someone else's code; I just want to install the same service on my new server that is already running on the old server.

How do I fix this and get it working?

**Comment by orgads** [comment]
ping

**Comment by Fearodin** [comment]
as of july 2022 it's still an issue...

**Comment by coreybutler** [comment]
@Fearodin - death in the family. Please be patient.

**Comment by Fearodin** [comment]
@coreybutler uff sry bro, my condolences!

**Comment by amoscatelli** [comment]
> @Fearodin - death in the family. Please be patient.

my condolences

**Comment by zeeshaanali** [comment]
> @Fearodin - death in the family. Please be patient.

I landed to this page for obvious reason. But sorry to hear, my condolences.

**Comment by VincentTungCW** [comment]
> For other noobs like me looking to reinvent the same solution of rolling back to 1.0.0-beta.6 Do the the following:
> 
> ```
> cd c:\path\to\index.js
> npm uninstall -g node-windows
> npm install -g node-windows@1.0.0-beta.6
> npm link node-windows
> ```
> 
> Then review your package.json file to ensure the correct node-windows version is listed in the dependencies section.

For who trying this, just incase it not auto delete files after uninstall, before start install 1.0.0-beta.6, we can double check and manual remove at 
C:\Users\{your_login}\AppData\Roaming\npm\node_modules\node-windows\

**Comment by bsikute** [comment]
> For other noobs like me looking to reinvent the same solution of rolling back to 1.0.0-beta.6 Do the the following:
> 
> ```
> cd c:\path\to\index.js
> npm uninstall -g node-windows
> npm install -g node-windows@1.0.0-beta.6
> npm link node-windows
> ```
> 
> Then review your package.json file to ensure the correct node-windows version is listed in the dependencies section.

this has worked for me. thank you

**Comment by mauriciojaramillo** [comment]
Hi folks.

I solved the problem changing (fixing) the path to the node-windows folder in the nnn.XML file in the bin/daemon folder.

My problem was due to join the server to the Windows Active Directory; after this action the path to the user profile is different and need to be fixed in the nnn.XML file.

I hope this help someone like me.

**Comment by coreybutler** [comment]
After going through the code, I decided to implement yargs in order to unblock folks. This has been released as 1.0.0-beta.8. Further comments in discussion https://github.com/coreybutler/node-windows/discussions/309.
